version: 2.1

#orbs:
#  welcome: circleci/welcome-orb@0.4.1

jobs:
  build-debian:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Debian build
          command: |
            echo Debian build

  platform-build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Platform build
          command: |
            echo Platform build

  master-job:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive
      - run:
          name: Master commit message
          command: |
            echo Commit applied on master

  version-tag-job:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive
      - run:
          name: Version tag message
          command: |
            echo Version tag applied

  deploy-release:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Deploy release
          command: |
            echo Deploy release

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      ignore: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

on-integration-branch: &on-integration-branch
  filters:
    branches:
      only: "1.0"

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-master-and-version-tags: &on-master-and-version-tags
  filters:
    branches:
      only: master
    tags:
      only: /^v[0-9].*/

platform-build-defs: &platform-build-defs
  requires:
    - build-debian

after-platform-builds: &after-platform-builds
  requires:
    - build-bionic

workflows:
  version: 2
  all-branches:
    jobs:
      - build-debian:
          <<: *on-any-branch
  integration-branches:  
    when:
      and:
        - equal: [<<pipeline.git.branch>>, 1.0]
    jobs:
      - build-debian:
          <<: *on-integration-branch
      - platform-build:
          name: build-bionic
          <<: *platform-build-defs
      - deploy-release:
          <<: *after-platform-builds
          <<: *on-version-tags
  