version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  version-tag-job:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive
      - run:
          name: Version tag message
          command: |
            echo Version tag applied

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-master-and-version-tags: &on-master-and-version-tags
  filters:
    branches:
      only:
        - master
    tags:
      only: /^v[0-9].*/

workflows:
  version: 2
  welcome:
    jobs:
      - welcome/run
  version-tag-job:
    jobs:
      - version-tag-job:
          <<: *on-version-tags
