name: CLang (container)

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        default: '["ubuntu:jammy", "ubuntu:bionic", "centos:7", "rockylinux:8", "debian:buster"]'

jobs:
  clang-test-with-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms) }}
    container:
      image: ${{ matrix.OS }}
#      volumes:
#        - /lab:/lab
      options: --cpus 2
    steps:
      - name: Get git
        run: |
          if command -v apt-get 2>&1 /dev/null; then apt-get -qq update; apt-get install -y git; fi
          if command -v yum 2>&1 /dev/null; then yum install -y git; fi
      - name: Checkout and build
        run: |
          mkdir -p /build
          cd /build
          git clone --recursive https://github.com/RedisLabsModules/readies.git
          git clone --recursive -j8 https://github.com/RedisBloom/RedisBloom.git
          cd readies
          ./bin/getget
          ./bin/getpy3
          ./bin/getclang --modern
          clang --version
          cd /build/RedisBloom
          ./sbin/setup
          bash -l -c "make CLANG=1"
