name: CLang (container)

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        default: '["ubuntu:jammy", "ubuntu:bionic", "centos:7", "rockylinux:8", "debian:buster"]'

jobs:
  clang-test-with-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms) }}
    container:
      image: ${{ matrix.OS }}
#      volumes:
#        - /lab:/lab
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: Checkouts
        run: |
          mkdir -p /build
          cd /build
          git clone --recursive https://github.com/RedisLabsModules/readies.git
          git clone --recursive -j8 https://github.com/RedisBloom/RedisBloom.git
      - name: Get CLang
        run: |
          cd /build/readies
          ./bin/getget
          ./bin/getpy3
          ./bin/getclang --modern
          clang --version
      - name: Build module
        run: |
          cd /build/RedisBloom
          ./sbin/setup
          bash -l -c "make CLANG=1"
