name: CLang (container)

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        default: '["ubuntu:jammy", "ubuntu:bionic", "centos:7", "rockylinux:8", "debian:buster"]'

jobs:
  clang-test-with-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms) }}
    container:
      image: ${{ matrix.OS }}
      volumes:
        - /build:/build
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
        with:
          repository: RedisLabsModules/readies
          path: /build/readies
      - uses: actions/checkout@v3
        with:
          repository: RedisBloom/RedisBloom
          path: /build/RedisBloom
          submodules: true
      - name: Get CLang
        run: |
          cd /build/readies
          ./bin/getget
          ./bin/getpy3
          ./bin/getclang --modern
          clang --version
      - name: Build module
        run: |
          cd /build/RedisBloom
          ./sbin/setup
          bash -l -c "make CLANG=1"
