name: CLang

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        default: '["ubuntu:jammy", "ubuntu:bionic", "centos:7", "rockylinux:8", "debian:buster"]'

jobs:
  clang-test-with-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms) }}
    container:
      image: ${{ matrix.OS }}
#      volumes:
#        - /lab:/lab
      options: --cpus 4
    steps:
    - name: Build container
      run: |
        mkdir -p /build
        cd /build
        git clone --recursive https://github.com/RedisLabsModules/readies.git
        git clone --recursive -j8 https://github.com/RedisBloom/RedisBloom.git
        cd readies
        ./bin/getget
        ./bin/getpy3
        ./bin/getclang --modern
        clang --version
        cd /build/RedisBloom
        ./sbin/setup
        bash -l -c "make CLANG=1"
