name: Manual

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
#  printInputs:
#    runs-on: ubuntu-latest
#    steps:
#    - run: |
#        echo "Log level: ${{ github.event.inputs.logLevel }}"
#        echo "Tags: ${{ github.event.inputs.tags }}"

#  clang-test-with-container:
#    runs-on: ubuntu-latest
#    container:
#      image: ubuntu:jammy
#      env:
#        NODE_ENV: development
#      ports:
#        - 80
#      volumes:
#        - lab:/lab
#      options: --cpus 1
#    steps:
#      - name: Check for dockerenv file
#        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

  clang-test-via-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Prerequisites
      run: |
        git clone --recursive https://github.com/RedisLabsModules/readies.git
        ./readies/bin/getget
        ./readies/bin/getdocker
    - name: Build container
      run: |
        cd clang-build
        git clone --recursive -j8 https:/github.com/RedisBloom/RedisBloom.git
        ln -s ../readies readies
        docker build .
